
package https.common_checkout_cdc_nicusa;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.datacontract.schemas._2004._07.common_payment.GetPaymentInfoResponse;
import org.datacontract.schemas._2004._07.common_payment.PaymentInfo;
import org.datacontract.schemas._2004._07.common_payment.PaymentInfov2;
import org.datacontract.schemas._2004._07.common_payment.PaymentResult;
import org.datacontract.schemas._2004._07.common_payment.PreparePaymentResult;
import org.datacontract.schemas._2004._07.common_payment.PreparePaymentv2Result;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.6 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebService(name = "IServiceWeb", targetNamespace = "https://common.checkout.cdc.nicusa.com")
@XmlSeeAlso({
    org.datacontract.schemas._2004._07.common_payment.ObjectFactory.class,
    com.microsoft.schemas._2003._10.serialization.ObjectFactory.class,
    https.common_checkout_cdc_nicusa.ObjectFactory.class
})
public interface IServiceWeb {


    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.common_payment.PreparePaymentResult
     */
    @WebMethod(operationName = "PreparePayment", action = "https://common.checkout.cdc.nicusa.com/IServiceWeb/PreparePayment")
    @WebResult(name = "PreparePaymentResult", targetNamespace = "https://common.checkout.cdc.nicusa.com")
    @RequestWrapper(localName = "PreparePayment", targetNamespace = "https://common.checkout.cdc.nicusa.com", className = "https.common_checkout_cdc_nicusa.PreparePayment")
    @ResponseWrapper(localName = "PreparePaymentResponse", targetNamespace = "https://common.checkout.cdc.nicusa.com", className = "https.common_checkout_cdc_nicusa.PreparePaymentResponse")
    public PreparePaymentResult preparePayment(
        @WebParam(name = "request", targetNamespace = "https://common.checkout.cdc.nicusa.com")
        PaymentInfo request);

    /**
     * 
     * @param request
     * @return
     *     returns org.datacontract.schemas._2004._07.common_payment.PreparePaymentv2Result
     */
    @WebMethod(operationName = "PreparePaymentv2", action = "https://common.checkout.cdc.nicusa.com/IServiceWeb/PreparePaymentv2")
    @WebResult(name = "PreparePaymentv2Result", targetNamespace = "https://common.checkout.cdc.nicusa.com")
    @RequestWrapper(localName = "PreparePaymentv2", targetNamespace = "https://common.checkout.cdc.nicusa.com", className = "https.common_checkout_cdc_nicusa.PreparePaymentv2")
    @ResponseWrapper(localName = "PreparePaymentv2Response", targetNamespace = "https://common.checkout.cdc.nicusa.com", className = "https.common_checkout_cdc_nicusa.PreparePaymentv2Response")
    public PreparePaymentv2Result preparePaymentv2(
        @WebParam(name = "request", targetNamespace = "https://common.checkout.cdc.nicusa.com")
        PaymentInfov2 request);

    /**
     * 
     * @param token
     * @return
     *     returns org.datacontract.schemas._2004._07.common_payment.PaymentResult
     */
    @WebMethod(operationName = "QueryPayment", action = "https://common.checkout.cdc.nicusa.com/IServiceWeb/QueryPayment")
    @WebResult(name = "QueryPaymentResult", targetNamespace = "https://common.checkout.cdc.nicusa.com")
    @RequestWrapper(localName = "QueryPayment", targetNamespace = "https://common.checkout.cdc.nicusa.com", className = "https.common_checkout_cdc_nicusa.QueryPayment")
    @ResponseWrapper(localName = "QueryPaymentResponse", targetNamespace = "https://common.checkout.cdc.nicusa.com", className = "https.common_checkout_cdc_nicusa.QueryPaymentResponse")
    public PaymentResult queryPayment(
        @WebParam(name = "token", targetNamespace = "https://common.checkout.cdc.nicusa.com")
        String token);

    /**
     * 
     * @param token
     * @return
     *     returns org.datacontract.schemas._2004._07.common_payment.GetPaymentInfoResponse
     */
    @WebMethod(operationName = "GetPaymentInfo", action = "https://common.checkout.cdc.nicusa.com/IServiceWeb/GetPaymentInfo")
    @WebResult(name = "GetPaymentInfoResult", targetNamespace = "https://common.checkout.cdc.nicusa.com")
    @RequestWrapper(localName = "GetPaymentInfo", targetNamespace = "https://common.checkout.cdc.nicusa.com", className = "https.common_checkout_cdc_nicusa.GetPaymentInfo")
    @ResponseWrapper(localName = "GetPaymentInfoResponse", targetNamespace = "https://common.checkout.cdc.nicusa.com", className = "https.common_checkout_cdc_nicusa.GetPaymentInfoResponse")
    public GetPaymentInfoResponse getPaymentInfo(
        @WebParam(name = "token", targetNamespace = "https://common.checkout.cdc.nicusa.com")
        String token);

}
